---
- name: Install Patroni
  apt:
    name: patroni
    state: present
    update_cache: yes

- name: Ensure Patroni service is started
  service:
    name: patroni
    state: started
    enabled: yes

- name: Copy Patroni configuration template
  template:
    src: templates/patroni.yml.j2
    dest: /etc/patroni.yml
    owner: postgres
    group: postgres
    mode: '0644'

- name: Copy Patroni systemd service file
  template:
    src: templates/patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and start Patroni service
  service:
    name: patroni
    state: started
    enabled: yes
