---
- name: Ensure the postgres user exists
  user:
    name: postgres
    state: present
    shell: /bin/bash
    create_home: yes

- name: Ensure postgres user has correct permissions
  file:
    path: /var/lib/postgresql
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Install boto3 and botocore via pip
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    executable: pip3
  become: true