---
- name: Clone etcd repository
  git:
    repo: https://github.com/etcd-io/etcd.git
    dest: /opt/etcd
    version: v3.5.21

- name: Build etcd binaries
  command: ./build.sh
  args:
    chdir: /opt/etcd
  when: ansible_distribution == "Amazon"

- name: Add etcd binaries to PATH
  lineinfile:
    path: /etc/profile.d/etcd.sh
    line: 'export PATH="$PATH:/opt/etcd/bin"'
    create: yes
    state: present
  notify: Refresh environment

- name: Verify etcd installation
  shell: |
    source /etc/profile.d/etcd.sh
    etcd --version
  register: etcd_version
  changed_when: false
  failed_when: "'etcd Version' not in etcd_version.stdout"

- name: Print etcd version
  debug:
    msg: "{{ etcd_version.stdout }}"
