---
- name: Define etcd version
  set_fact:
    etcd_version: "v3.5.14"

- name: Download etcd release tarball
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    dest: "/tmp/etcd.tar.gz"
    mode: '0644'

- name: Extract etcd archive
  unarchive:
    src: "/tmp/etcd.tar.gz"
    dest: "/opt/"
    remote_src: yes

- name: Move etcd binaries to /usr/local/bin
  copy:
    remote_src: yes
    src: "/opt/etcd-{{ etcd_version }}-linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
  loop:
    - etcd
    - etcdctl

- name: Verify etcd installation
  command: etcd --version
  register: etcd_version_output
  changed_when: false

- name: Show etcd version
  debug:
    msg: "{{ etcd_version_output.stdout_lines }}"
