---

- name: Install etcd
  include_tasks: install.yml

- name: Create etcd system user
  user:
    name: etcd
    system: yes
    shell: /sbin/nologin
    create_home: no
    
- name: Ensure etcd configuration directory exists
  file: 
    path: "{{ etcd_config_path }}"
    state: directory
    owner: "{{ etcd_owner }}"
    group: "{{ etcd_group }}"
    mode: "{{ etcd_data_dir_mode }}"

- name: Copy etcd configuration template
  template:
    src: templates/etcd.conf.yml.j2
    dest: "{{ etcd_config_file }}"
    owner: "{{ etcd_owner }}"
    group: "{{ etcd_group }}"
    mode: "{{ etcd_config_mode }}"
  notify: Restart etcd

- name: Ensure etcd data directory exists
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    owner: "{{ etcd_owner }}"
    group: "{{ etcd_group }}"
    mode: "{{ etcd_data_dir_mode }}"

# - name: Check etcd health
#   command: etcdctl endpoint health --endpoints={{ etcd_listen_client_urls }}
#   register: etcd_health_check
#   changed_when: false
#   until: "'is healthy' in etcd_health_check.stdout"
#   retries: 5
#   delay: 5 
#   failed_when: "etcd_health_check.rc != 0"
#   ignore_errors: yes

# - name: Debug etcd health status
#   debug:
#     msg: "Etcd health check result: {{ etcd_health_check.stdout }}"
