---
- name: Install etcd
  apt:
    name: etcd
    state: present
    update_cache: yes

- name: Ensure etcd service is started
  service:
    name: etcd
    state: started
    enabled: yes

- name: Copy etcd configuration template
  template:
    src: templates/etcd.conf.yml.j2
    dest: /etc/etcd/etcd.conf.yml
    owner: etcd
    group: etcd
    mode: '0644'
  notify: Restart etcd

- name: Ensure /var/lib/etcd directory exists
  file:
    path: /var/lib/etcd
    state: directory
    owner: etcd
    group: etcd
    mode: '0700'
