---
- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted

- name: Restart Patroni
  service:
    name: patroni
    state: restarted

- name: Clean DNF metadata
  ansible.builtin.command: dnf clean all
  become: true