# This playbook installs PostgreSQL 15 on a RHEL 8 system using the official PGDG repository.
---

- name: Ensure PostgreSQL service is started
  dnf:
    name: postgresql15-server.x86_64
    state: present
    