# This playbook installs PostgreSQL 15 on a RHEL 8 system using the official PGDG repository.
---

- name: Install PostgreSQL 15 on RHEL 8
  dnf:
    name: postgresql15-server.x86_64
    state: present

- name: Install PostgreSQL client
  dnf:
    name: postgresql15.x86_64
    state: present

# Initialize the PostgreSQL database
- name: Initialize PostgreSQL database
  command: postgresql-setup initdb
  args:
    creates: /etc/postgresql/postgresql.conf

- name: Ensure PostgreSQL service is enabled and started
  service:
    name: postgresql
    state: started
    enabled: yes
