- name: Create dummy /etc/redhat-release file for PostgreSQL repo compatibility
  ansible.builtin.copy:
    dest: /etc/redhat-release
    content: "Red Hat Enterprise Linux release 8.0 (Ootpa)\n"
    mode: '0644'
  become: true

- name: Download PGDG repo RPM to /tmp
  ansible.builtin.get_url:
    url: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    dest: /tmp/pgdg-redhat-repo.rpm
    mode: '0644'
  become: true

- name: Install PGDG repo RPM using rpm (bypassing dependency check)
  ansible.builtin.command:
    cmd: rpm -i --nodeps /tmp/pgdg-redhat-repo.rpm
  args:
    creates: /etc/yum.repos.d/pgdg-redhat-all.repo
  become: true

- name: Remove dummy /etc/redhat-release
  ansible.builtin.file:
    path: /etc/redhat-release
    state: absent
  become: true
