# This playbook installs PostgreSQL 15 on a RHEL 8 system using the official PGDG repository.
---

- name: Install PostgreSQL 15 on RHEL 8
  dnf:
    name: postgresql15-server.x86_64
    state: present

- name: Install PostgreSQL client
  dnf:
    name: postgresql15.x86_64
    state: present
- name: Remove conflicting packages
  dnf:
    name: libpq-devel
    state: absent

- name: Install PostgreSQL additional packages
  dnf:
    # Refers to each item in the loop below
    name: "{{item}}"
  loop: 
  - postgresql15-contrib
  - postgresql15-devel

- name: Ensure PostgreSQL service is enabled and stopped
  service:
    name: postgresql
    state: stopped
    enabled: yes
