---
- name: Download PostgreSQL tarball
  get_url:
    url: "{{ download_url }}"
    dest: "/tmp/postgresql.tar.gz"
    mode: '0644'

- name: Extract PostgreSQL tarball
  unarchive:
    src: "/tmp/postgresql.tar.gz"
    dest: "/opt/"
    remote_src: yes

- name: Move PostgreSQL binaries to /usr/local/bin
  copy:
    remote_src: yes
    src: "/opt/postgresql-{{ postgres_version }}/src/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
  loop:
    - initdb
    - pg_ctl
    - postgres
    - psql

- name: Verify PostgreSQL installation
  command: psql --version
  register: postgres_version_output
  changed_when: false

- name: Show PostgreSQL version
  debug:
    msg: "{{ postgres_version_output.stdout_lines }}"
