---

- name: Ensure PostgreSQL data directory exists
  file:
    state: directory
    path: "{{postgres_data_directory}}"
    owner: postgres
    group: postgres
    mode: '0700'

- name: Ensure the postgres user exists
  user:
    name: postgres
    state: present
    shell: /bin/bash
    create_home: yes

- name: Ensure PostgreSQL config directory exists
  file:
    state: directory
    path: "{{postgres_conf_directory}}"
    owner: postgres
    group: postgres
    mode: '0700'



- name: Install PostgreSQL
  ansible.builtin.include_tasks:
    file: install.yml


- name: Copy PostgreSQL configuration template
  template:
    src: templates/postgresql.conf.j2
    dest: "{{postgres_conf_directory}}/postgresql.conf"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    mode: '0644'

# - name: retart PostgreSQL service after installation
#   service:
#     name: postgresql
#     state: restarted
