---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

- name: Ensure PostgreSQL service is started
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Copy PostgreSQL configuration template
  template:
    src: templates/postgresql.conf.j2
    dest: /etc/postgresql/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0644'
