---
- name: Install PostgreSQL
  ansible.builtin.include_tasks:
    file: install.yml


- name: Ensure PostgreSQL data directory exists
  file:
    state: directory
    path: '/var/lib/postgresql/data'
    owner: postgres
    group: postgres
    mode: '0700'

- name: Copy PostgreSQL configuration template
  template:
    src: templates/postgresql.conf.j2
    dest: /etc/postgresql/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0644'

- name: Stop PostgreSQL service after installation
  service:
    name: postgresql
    state: stopped
