---
postgres_version: 13
patroni_version: latest
postgres_listen_addresses: '{{ ansible_default_ipv4.address }}'
postgres_port: 5432
postgres_max_connections: 200
postgres_shared_buffers: '256MB'
postgres_logging_collector: 'on'
postgres_log_directory: '/var/log/postgresql'
postgres_data_directory: '/var/lib/postgresql/data'
postgres_conf_directory: '/etc/postgresql/''
postgres_log_filename: 'postgresql.log'
