all:
  hosts:
    localhost:
      ansible_connection: local
      # Variables for the localhost (control node itself)
      node_name: "postgres-primary-1"
      aws_region: "eu-west-3"
      # List of PostgreSQL instance IPs gathered from AWS
      postgres_ips:
            - 10.12.1.160
            - 10.11.1.195
            - 10.11.2.227
