all:
  hosts:
    localhost:
      ansible_connection: local
      # Variables for the localhost (control node itself)
      node_name: "postgres-primary-1"
      aws_region: "eu-west-3"
      etcd_node: "node-eu-west-3-1"
      # List of PostgreSQL instance IPs gathered from AWS
      postgres_ips:
        - { name: postgres-primary-1, ip: 10.11.1.89, etcd_node: node-eu-west-3-1 }
        - { name: postgres-primary-2, ip: 10.11.2.243, etcd_node: node-eu-west-3-2 }
